export const WORDS: string[] = [
  'Performant',
  'Interactive',
  'Scalable',
  'User-Friendly',
  'Responsive',
  'Maintainable',
  'Reliable',
  'Detail-Oriented',
  'Full-Stack',
  'Problem-Solver',
  'Clean Code',
  'Modern Tech',
  'UI/UX Focused',
  'Best Practices',
  'Adaptable',
  'Collaborative',
  'Innovative',
];
